#pragma once

#include "NativeGameplayTags.h"

namespace AlsTags
{
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Root)
}

namespace AlsDesiredStateTags
{
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Root)
}

namespace AlsDesiredViewModeTags
{
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Root)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FirstPerson)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ThirdPerson)
}

namespace AlsDesiredRotationModeTags
{
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Root)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(VelocityDirection)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ViewDirection)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Aiming)
}

namespace AlsDesiredStanceTags
{
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Root)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Standing)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Crouching)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LyingFront)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LyingBack)
}

namespace AlsDesiredGaitTags
{
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Root)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Walking)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Running)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sprinting)
}

namespace AlsViewModeTags
{
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Root)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FirstPerson)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ThirdPerson)
}

namespace AlsLocomotionModeTags
{
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Root)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Grounded)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InAir)
}

namespace AlsRotationModeTags
{
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Root)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(VelocityDirection)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ViewDirection)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Aiming)
}

namespace AlsAimingModeTags
{
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Root)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(AimDownSight)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(HipFire)
}

namespace AlsStanceTags
{
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Root)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Standing)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Crouching)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LyingFront)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LyingBack)
}

namespace AlsGaitTags
{
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Root)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Walking)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Running)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sprinting)
}

namespace AlsOverlayModeTags
{
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Root)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Default)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Masculine)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Feminine)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Injured)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(HandsTied)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(M4)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PistolOneHanded)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PistolTwoHanded)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Bow)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Torch)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Binoculars)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Box)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Barrel)
}

namespace AlsLocomotionActionTags
{
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Root)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Rolling)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Landing)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Mantling)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Vaulting)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GettingUp)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GettingDown)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FreeFalling)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(BeingKnockedDown)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Dying)
}

namespace AlsStateFlagTags
{
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Root)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LeftShoulder)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FacingUpward)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(DelayedActivation)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MantleHigh)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MantleMedium)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MantleLow)
}

namespace AlsGroundedEntryModeTags
{
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Root)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(CrouchingToStanding)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(StandingToCrouching)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(CrouchingToLyingBack)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(CrouchingToLyingFront)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LyingBackToCrouching)
	ALS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LyingFrontToCrouching)
}
