#pragma once

#include "NativeGameplayTags.h"

namespace AlsCameraTags
{
	ALSCAMERA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Root)
}

namespace AlsCameraViewModeTags
{
	ALSCAMERA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Root)
	ALSCAMERA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FirstPerson)
	ALSCAMERA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ThirdPerson)
}

namespace AlsCameraShoulderModeTags
{
	ALSCAMERA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Root)
	ALSCAMERA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Center)
	ALSCAMERA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Left)
	ALSCAMERA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Right)
}
